//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL1_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public int CLASS_ID { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<int> PROF_ID { get; set; }
        public Nullable<int> COURSE_ID { get; set; }
        public Nullable<int> ROOM_ID { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual PROFESSOR PROFESSOR { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
