//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL1_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCHOOL1Entities : DbContext
    {
        public SCHOOL1Entities()
            : base("name=SCHOOL1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLASS> CLASSes { get; set; }
        public DbSet<COURSE> COURSEs { get; set; }
        public DbSet<PROFESSOR> PROFESSORs { get; set; }
        public DbSet<ROOM> ROOMs { get; set; }
        public DbSet<STUDENT_> STUDENT_ { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
