//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL1_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_
    {
        public int STUD_ID { get; set; }
        public string STUD_FNAME { get; set; }
        public string STUD_LNAME { get; set; }
        public string STUD_STREET { get; set; }
        public string STUD_CITY { get; set; }
        public string STUD_ZIP { get; set; }
    }
}
