//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_Type
    {
        public Album_Type()
        {
            this.Albums = new HashSet<Album>();
        }
    
        public int Type_ID { get; set; }
        public string Type_Desc { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
    }
}
