//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Stock_Item = new HashSet<Stock_Item>();
        }
    
        public int Branch_ID { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<int> Branch_Floor_Size { get; set; }
        public string Branch_Phone { get; set; }
        public string Branch_Address { get; set; }
        public string Branch_Contact_Name { get; set; }
        public string Branch_City { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Stock_Item> Stock_Item { get; set; }
    }
}
