//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Invoice_Line = new HashSet<Invoice_Line>();
        }
    
        public int Invoice_Num { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Customer_Acc_No { get; set; }
        public Nullable<System.DateTime> Invoice_date { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Invoice_Line> Invoice_Line { get; set; }
    }
}
