//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Line
    {
        public int Invoice_Num { get; set; }
        public string Album_ISBN { get; set; }
        public Nullable<int> Purchase_Quantity { get; set; }
        public Nullable<decimal> Item_Unit_Price { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Stock_Item Stock_Item { get; set; }
    }
}
