//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicologyWarehouseEntities : DbContext
    {
        public MusicologyWarehouseEntities()
            : base("name=MusicologyWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Albums { get; set; }
        public DbSet<Album_Category> Album_Category { get; set; }
        public DbSet<Album_Price> Album_Price { get; set; }
        public DbSet<Album_Type> Album_Type { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<Invoice_Line> Invoice_Line { get; set; }
        public DbSet<Stock_Item> Stock_Item { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
