//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Item
    {
        public Stock_Item()
        {
            this.Invoice_Line = new HashSet<Invoice_Line>();
        }
    
        public string Album_ISBN { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Stock_Total_Quantity { get; set; }
        public Nullable<int> Stock_Quantity_Sold { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Invoice_Line> Invoice_Line { get; set; }
    }
}
